@startuml

title Send Ticket Sales to CTC

skinparam noteBorderColor #049595

skinparam sequence {
  BackgroundColor transparent
  ParticipantBackgroundColor #e6ffcc
  ParticipantBorderColor 	#049595
  noteBorderColor 	#049595
  PackageBorderCOlor  #049595
  ArrowColor #006666
  LifeLineBorderColor #c09cd9
}

participant TrackModel
box "CTC"
participant Ctc
participant CtcGui
end box

activate TrackModel
TrackModel -> TrackModel : generateTicketSales()
note left: If there is a train\narriving at station...
TrackModel -> Ctc : addTicketSales(numTickets)
deactivate TrackModel

activate Ctc
Ctc -> Ctc : Add ticket to runningTicketSales
group calculateThroughput()
Ctc -> Ctc : Throughput = Σ tickets/(currTime-beginTime)
Ctc -> CtcGui : repaint()
end
note right
This section is run
every clock cycle
end note
deactivate Ctc


@enduml
