@startuml

title Set Train CTC Authority

skinparam sequence {
  BackgroundColor transparent
  ParticipantBackgroundColor #e6ffcc
  ParticipantBorderColor 	#049595
  PackageBorderCOlor  #049595
  ArrowColor #006666
  LifeLineBorderColor #c09cd9
}

box "Ctc"
participant Ctc
participant Train
participant Block
end box
participant TrackController
participant TrackModel
participant TrainModel
participant Mbo
group Every clock tick for every train
  activate Ctc

  Ctc -> Train : getNextStop()
    activate Train
  Train --> Ctc : nextStop
  Ctc -> Train : getLocation()
  Train --> Ctc : block
  deactivate Train
  group while(block!=nextStop)
    Ctc -> Block : block.getLength()
    activate Block
    Block -> Ctc : length
    deactivate Block
    Ctc -> Ctc : authority+=length
    Ctc -> Ctc : block = block.next
  end
  Ctc -> TrackController : transmitCtcAuthority(Train,authority)
  deactivate Ctc

  activate TrackController
  TrackController -> TrackModel : transmitCtcAuthority(Train,authority)
  deactivate TrackController

  activate TrackModel
  TrackModel -> TrainModel : transmitCtcAuthority(Train,authority)
  deactivate TrackModel

  activate TrainModel
  TrainModel -> TrainController : setCtcAuthority(Train,authority)
  activate TrainController

  activate Mbo
  Mbo -> Mbo : Determine authority
  Mbo -> TrainController : setMboAuthority(Train, authority)
  deactivate Mbo

  TrainController --> TrainController : setAuthority(ctcAuthority,mboAuthority)
  deactivate TrainController

  deactivate TrainModel
end
@enduml
