@startuml

title CTC
skinparam backgroundColor transparent
skinparam classBackgroundColor #e6ffcc
skinparam classBorderColor 	#049595
skinparam packageBorderCOlor  #049595
skinparam arrowColor #006666


package Shared{
  interface Module{
    +timeUpdate(SimTime) : Boolean
  }
  class SimTime{
    +hr : int
    +min : int
    +sec : int
    +toString() : String
  }
}
package Module.Ctc {
  class Ctc {
    +simulator : Simulator
    +trkctl : TrackController
    +trnmdl : TrainModel
    +trnctl : TrainController
    -ctcGui : CtcGui
    -beginTime : SimTime
    -currentTime : SimTime
    +trains : Train[]
    +schedulesInQueue : Schedule[]
    +blocks : Block[]
    -runningTicketSales : int
    -throughput : double
    __
    ..Schedule Creation and Queue..
    +importSchedule(String)
    +addScheduleToQueue(String,Schedule)
    +dispatchTrainFromQueue(String)
    -dispatchTrainFromQueue(String,String,int)
    -dispatchTrainFromQueue(String,String,int,String[])
    +updateSchedule(String,Schedule)
    ..Train Communication..
    -transmitSuggestedSetpointSpeed(String,int)
    -transmitSuggestedSetpointSpeed(String,int)
    -transmitCtcAuthority(String,double)
    ..Block Communication..
    -receiveBlockOccupancy(String,int)
    -receiveBlockStatus(String,int)
    -receiveSwitchState(String,int)
    -transmitSwitchState(String,int,boolean)
    -transmitBlockMaintenance(String,int) : Boolean
    ..Throughput..
    -calculateThroughput() : double
    +addTicketSales(int)
    +getThroughput() : double
    ..Helpers..
    -calculateAuthority(String) : double
    -getQueuedScheduleByName(String) : Schedule
    -getTrainByName(String) : Train
    -getBlockByNumber(String,int) : Block
  }
  class CtcGui {
    +ctc : Ctc
    -createSchedule(Schedule) : Schedule
    -editSchedule(Schedule) : Schedule
    +repaint()
  }
  class ScheduleEditorGui {
    -ctcGui : CtcGui
    -submitScheduleToCtc()
  }
  class Train{
    -schedule : Schedule
    -line : String
    -location : int
    -speed : int
    -authority : int
    -passengers : int
    -nextStop : String
    __
    ..Getters..
    +getSchedule() : Schedule
    +getNextStop() : String
    +getLine() : String
    +getSpeed() : int
    +getAuthority() : int
    +getPassengers() : int
    ..Setters..
    +setSchedule(Schedule)
    +setSpeed(int)
    +setAuthority(int)
    +addPassengers(int)
    +removePassengers(int)
  }
  class Schedule {
    +stops : Stop[]
    +departureTime : SimTime
    +line : String
    +name : String
    +authority : int
    +dispatched : Boolean
    +toStringArray() : String
  }
  class Stop {
    +location : Block
    +arrivalTime : SimTime
    +departureTime : SimTime
  }
  class Block{
    ..General..
    +line : String
    +number : int
    ..Station..
    +isStation : Boolean
    +stationName : String
    ..Station..
    +isSwitch : Boolean
    +switchState : Boolean
    __
  }
}

Module--SimTime : imports

Module <|. Ctc : implements

Ctc o->"0..*" Block : has knowledge of
Ctc o->"0..*" Schedule : contains in queue
Ctc o-->"0..*" Train : monitors
Ctc *-"1" CtcGui : instantiates

CtcGui *-"1" ScheduleEditorGui : instantiates

Schedule o->"1..*" Stop : contains
Stop o->"1" Block : located at

Train *->"1" Schedule : is following
Train o->"1" Block : located at

@enduml
