@startuml

title Close Track For Maintenance & Repair Track

skinparam sequence {
  BackgroundColor transparent
  ParticipantBackgroundColor #e6ffcc
  ParticipantBorderColor 	#049595
  PackageBorderCOlor  #049595
  ArrowColor #006666
  LifeLineBorderColor #c09cd9
}

participant Ctc
participant TrackController
participant TrackModel

activate Ctc
Ctc -> Ctc : Select Block
Ctc -> TrackController : setSwitchStatus(Block,direction)

activate TrackController
TrackController -> TrackModel : setSwitchStatus(Block,direction)

activate TrackModel
TrackModel -> TrackModel : setSwitchStatus(direction)
TrackModel --> TrackController : //new switch status//
deactivate TrackModel

TrackController -> TrackController : updateSwitchStatus(Block,status)
TrackController --> Ctc : //new switch status//
deactivate TrackController

Ctc -> Ctc : updateSwitchStatus(Block,status)
deactivate Ctc
@enduml
