@startuml

title Transmit Beacon Information

skinparam noteBorderColor #049595

skinparam sequence {
	BackgroundColor transparent
	ParticipantBackgroundColor #e6ffcc
	ParticipantBorderColor 	#049595
	PackageBorderCOlor  #049595
	ArrowColor #006666
	LifeLineBorderColor #c09cd9
}

participant TrackModel
participant TrainModel
participant TrainController

activate TrackModel
TrackModel -> TrainModel : setBeacon(block, beacon info)
note left: If a train passes a beacon...
deactivate TrackModel

activate TrainModel
TrainModel -> TrainModel : getTrainAtBlock(block)
TrainModel -> TrainController : setBeacon(train, beacon info)
deactivate TrainModel
activate TrainController
TrainController -> TrainController : decodeBeacon(train, beacon info)

@enduml