@startuml

title Manually Dispatch Train to Block

skinparam sequence {
  BackgroundColor transparent
  ParticipantBackgroundColor #e6ffcc
  ParticipantBorderColor 	#049595
  PackageBorderCOlor  #049595
  ArrowColor #006666
  LifeLineBorderColor #c09cd9
}
box "CTC"
actor Dispatcher
participant CtcGui
participant ScheduleEditor
participant Ctc
end box

participant TrainModel
participant TrainController
participant TrackModel

== Create the Schedule ==
activate CtcGui
Dispatcher -> CtcGui : Create New Schedule
activate ScheduleEditor
CtcGui -> ScheduleEditor : initialize()
Dispatcher -> ScheduleEditor : Create the Schedule
Dispatcher -> ScheduleEditor : Request Schedule be Added to Queue
ScheduleEditor -> Ctc : addScheduleToQueue(Schedule)
deactivate ScheduleEditor
Ctc -> CtcGui : repaint()
deactivate CtcGui
== Dispatch the Train ==
Ctc -> Ctc : dispatchTrainFromQueue(Schedule)
Ctc -> TrainModel : dispatchTrain(line,startingBlock)
Ctc -> TrainController : dispatchTrain(line,startingBlock,Schedule)


activate TrainController
TrainController -> TrackModel : getBlockSpeedLimits(line)
TrackModel --> TrainController : speedLimits[]
deactivate TrainController

@enduml
