@startuml

title Manually Dispatch Train to Block

skinparam sequence {
  BackgroundColor transparent
  ParticipantBackgroundColor #e6ffcc
  ParticipantBorderColor 	#049595
  PackageBorderCOlor  #049595
  ArrowColor #006666
  LifeLineBorderColor #c09cd9
}
box "CTC"
actor Dispatcher
participant CtcGui
participant ScheduleEditor
participant Ctc
participant Train
end box

participant TrainModel
participant TrainController
participant TrackModel

== Create the Schedule ==
activate CtcGui
Dispatcher -> CtcGui : Create New Schedule
activate ScheduleEditor
CtcGui -> ScheduleEditor : initialize()
...Create the Schedule...
Dispatcher -> ScheduleEditor : Request Schedule be Added to Queue
ScheduleEditor -> Ctc : addScheduleToQueue(Schedule)
activate Ctc
deactivate ScheduleEditor
Ctc -> CtcGui : repaint()
deactivate CtcGui
...Wait for Dispatch Time or Manual Start...
== Dispatch the Train ==
Ctc -> Train : new Train(Schedule)
Train --> Ctc : Train
activate CtcGui
Ctc -> CtcGui : repaint()
deactivate CtcGui

Ctc -> TrainModel : dispatchTrain(name,line,startingBlock)
Ctc -> TrainController : dispatchTrain(name,line,startingBlock,Schedule)
deactivate Ctc
activate TrainController
TrainController -> TrackModel : getBlockSpeedLimits(line)
activate TrackModel
TrackModel --> TrainController : speedLimits[]
deactivate TrackModel
deactivate TrainController

@enduml
