@startuml

title Send Ticket Sales to CTC

skinparam noteBorderColor #049595

skinparam sequence {
  BackgroundColor transparent
  ParticipantBackgroundColor #e6ffcc
  ParticipantBorderColor 	#049595
  noteBorderColor 	#049595
  PackageBorderCOlor  #049595
  ArrowColor #006666
  LifeLineBorderColor #c09cd9
}

participant TrackModel
box "CTC"
participant Ctc
participant Ticket
participant CtcGui
end box

activate TrackModel
TrackModel -> TrackModel : generateTicketSales()
note left: If there is a train\narriving at station...
TrackModel -> Ctc : addTicketSales(numTickets)
deactivate TrackModel

activate Ctc
Ctc -> Ticket : new Ticket (numTickets,currTime)
Ticket --> Ctc : Ticket
Ctc -> Ctc : Push Ticket to Ticket queue
group calculateThroughput()
Ctc -> Ctc : Peek at next Ticket in queue\nand remove if >1hr ago
Ctc -> Ctc : Throughput = Σ tickets in queue
Ctc -> CtcGui : repaint()
end
note right
This section is run
every clock cycle
end note
deactivate Ctc


@enduml
