@startuml

title Send Ticket Sales to CTC

skinparam noteBorderColor #049595

skinparam sequence {
  BackgroundColor transparent
  ParticipantBackgroundColor #e6ffcc
  ParticipantBorderColor 	#049595
  noteBorderColor 	#049595
  PackageBorderCOlor  #049595
  ArrowColor #006666
  LifeLineBorderColor #c09cd9
}

participant TrackModel
participant Ctc

activate TrackModel
TrackModel -> TrackModel : generateTicketSales()
note left: If there is a train...
TrackModel -> Ctc : addTicketSales(int)
deactivate TrackModel

activate Ctc
Ctc -> Ctc : calculateThroughput()
deactivate Ctc


@enduml
