@startuml
title Ctc Use Case Diagram
skinparam backgroundColor transparent'
skinparam usecaseBackgroundColor #e6ffcc
skinparam usecaseBorderColor 	#049595
skinparam actorBorderColor 	#049595
skinparam packageBorderColor  #049595
skinparam arrowColor #006666

:Ctc Officer: as c
:Dispatcher: as d
:Maintainer: as m
c <|-- d
c <|-- m
(Monitor overall train system) as mots
(Modify track status for\nmaintenance) as mts
d --> (Import a schedule)
d --> (Manually schedule a \nnew train)
d ---> (Dispatch a train)
d --> (Update a dispatched\ntrain's schedule)
d ---> (Suggest train\nspeed)
d --> (Set train authority)
d ---> (Toggle switch)
d --> mots
mots .->"<<include>>" (View train location)
mots .->"<<include>>" (View train speed)
mots .->"<<include>>" (View train authority)

m --> mts
mts .->"<<include>>" (Open the track)
mts .->"<<include>>" (Close the track)
@enduml
