@startuml

title Close Track For Maintenance & Repair Track

skinparam sequence {
  BackgroundColor transparent
  ParticipantBackgroundColor #e6ffcc
  ParticipantBorderColor 	#049595
  PackageBorderCOlor  #049595
  ArrowColor #006666
  LifeLineBorderColor #c09cd9
}

participant Ctc
participant TrackController
box
	participant TrackModel
	participant Block
end box

activate Ctc
Ctc -> Ctc : Select Block
Ctc -> TrackController : setBlockStatus(Block,"maintenance" or "open")

activate TrackController
TrackController -> TrackModel : setBlockStatus(Block,"maintenance" or "open")

activate TrackModel
TrackModel -> Block : setMaintenance("maintenance" or "open")
activate Block
deactivate TrackModel
Block --> TrackController : //new block status//
deactivate Block


TrackController -> TrackController : updateBlockStatus(status)
TrackController --> Ctc : //new block status//
deactivate TrackController

Ctc -> Ctc : updateBlockStatus(status)
deactivate Ctc
@enduml
