@startuml

title Toggle Switch

skinparam sequence {
  BackgroundColor transparent
  ParticipantBackgroundColor #e6ffcc
  ParticipantBorderColor 	#049595
  PackageBorderCOlor  #049595
  ArrowColor #006666
  LifeLineBorderColor #c09cd9
}

participant Ctc
participant TrackController
box
	participant TrackModel
	participant Block
	participant Switch
end box

activate Ctc
Ctc -> Ctc : Select Block
Ctc -> TrackController : setSwitchStatus(Block,direction)

activate TrackController
TrackController -> TrackModel : setSwitchStatus(Block,direction)

activate TrackModel
TrackModel -> TrackModel : getBlock()
	TrackModel -> Block : getSwitch()
deactivate TrackModel
		activate Block
			Block -> Switch : setSwitchState("normal" or "alternate")
					activate Switch
				deactivate Block
			Switch --> TrackController : //new switch status//
		deactivate Switch

TrackController -> TrackController : updateSwitchStatus(Block,status)
TrackController --> Ctc : //new switch status//
deactivate TrackController

Ctc -> Ctc : updateSwitchStatus(Block,status)
deactivate Ctc
@enduml
