@startuml

title Retrieve MBO Antenna Signal Sequence Diagram

skinparam sequence {
  BackgroundColor transparent
  ParticipantBackgroundColor #e6ffcc
  ParticipantBorderColor 	#049595
  BoxBorderColor #049595
  PackageBorderCOlor  #049595
  ArrowColor #006666
  LifeLineBorderColor #c09cd9
}

participant TrainModel
participant MBO


TrainModel -> MBO : getMboTrainModelntennaStatus()
activate TrainModel
activate MBO

MBO--> TrainModel : Return State

MBO-> TrainModel : getPos()

TrainModel --> MBO: Complete Request
deactivate TrainModel
deactivate MBO

@enduml