@startuml

title Create Train Schedule

skinparam sequence {
  BackgroundColor transparent
  ParticipantBackgroundColor #e6ffcc
  ParticipantBorderColor 	#049595
  PackageBorderCOlor  #049595
  ArrowColor #006666
  LifeLineBorderColor #c09cd9
}

participant MBOGui
participant MBOScheduler

== Update Individual Schedules, Generate Yard Schedule If Possible ==

activate MBOGui
activate MBOScheduler
MBOGui -> MBOScheduler : updateTrainSchedules(String[][])
MBOScheduler -> MBOGui : boolean trainSchedulesUpdated
MBOGui -> MBOScheduler : updateOperatorSchedules(String[][])
MBOScheduler -> MBOGui : boolean operatorSchedulesUpdated

group if (trainSchedulesUpdated & operatorSchedulesUpdated)
	MBOGui -> MBOScheduler : generateSchedule(String, double)
	MBOScheduler -> MBOGui : String schedule
end

@enduml