@startuml

title Get Authority

skinparam sequence {
  BackgroundColor transparent
  ParticipantBackgroundColor #e6ffcc
  ParticipantBorderColor 	#049595
  PackageBorderCOlor  #049595
  ArrowColor #006666
  LifeLineBorderColor #c09cd9
}

participant MBO

== MBO Receives Position and Transmits Authority ==
activate TrainController
activate MBO
MBO -> MBO : receiveTrainPosition(String)
MBO -> TrainController : getPosition(String)
TrainController -> MBO : trainPosition[2]
MBO -> MBO : calculateAuthority(String)
MBO -> MBO : transmitMboAuthority(String, double[2])
MBO -> TrainController : setMboAuthority(String, double)

@enduml