@startuml
title MBO Use Case Diagram

skinparam usecaseBackgroundColor #e6ffcc
skinparam usecaseBorderColor 	#049595
skinparam actorBorderColor 	#049595
skinparam packageBorderCOlor  #049595
skinparam arrowColor #006666

:Train Controller: as tc
:MBO Analyst: as ma
:Scheduler: as s

rectangle MBOGui{
	(View Data for Trains)
	(Create Train Schedule)
}

rectangle MBO {
	(Get Authority)
	(Get Safe Braking Distance)
}

ma --> (View Data for Trains)
tc --> (Get Authority)
tc --> (Get Safe Braking Distance)
s --> (Create Train Schedule)
@enduml