@startuml

title Train Model Use Case Diagram
'skinparam backgroundColor transparent'
skinparam usecaseBackgroundColor #e6ffcc
skinparam usecaseBorderColor 	#049595
skinparam actorBorderColor 	#049595
skinparam packageBorderCOlor  #049595
skinparam arrowColor #006666

:Passenger(s): as p
:Driver / Train Controller: as tnc
:MBO: as mbo

rectangle TrainModelGUI{
	(Activate Emergency Brake)
	(View Station Information)
	(View Speed/Authority Information)
    (Retrieve GPS Signal)
    (Retrieve MBO Antenna Signal)
}

p --> (Activate Emergency Brake)
p --> (View Station Information)
tnc --> (View Station Information)
tnc --> (View Speed/Authority Information)
tnc --> (Retrieve GPS Signal)
mbo --> (Retrieve MBO Antenna Signal)


    
@enduml