@startuml

title Train Model Use Case Diagram
'skinparam backgroundColor transparent'
skinparam usecaseBackgroundColor #e6ffcc
skinparam usecaseBorderColor 	#049595
skinparam actorBorderColor 	#049595
skinparam packageBorderCOlor  #049595
skinparam arrowColor #006666

:CTC: as ctc
:Passenger: as p
:Track Model: as tkm
:Train Controller: as tnc
:MBO: as mbo

rectangle TrainModelGUI{
    (Dispatch Train)
	(Activate Emergency Brake)
    (Retrieve Speed Information)
    (Retrieve Authority Information)
    (Retrieve GPS Signal)
    (Retrieve MBO Antenna Signal)
}

ctc --> (Dispatch Train)
p --> (Activate Emergency Brake)
tkm --> (Retrieve GPS Signal)
tnc --> (Retrieve GPS Signal)
tnc --> (Retrieve Speed Information)
tnc --> (Retrieve Authority Information)
mbo --> (Retrieve MBO Antenna Signal)


    
@enduml