@startuml

title Dispatch Train to Block

skinparam sequence {
  BackgroundColor transparent
  ParticipantBackgroundColor #e6ffcc
  ParticipantBorderColor 	#049595
  PackageBorderCOlor  #049595
  ArrowColor #006666
  LifeLineBorderColor #c09cd9
}
box "Ctc"
participant Ctc
participant CtcGui
end box
participant TrackController
participant TrackModel
participant TrainModel
']participant Mbo

activate Ctc
Ctc -> Ctc : Set suggested speed
Ctc -> TrackController : Transmit suggested speed
deactivate Ctc

activate TrackController
TrackController -> TrackModel : Transmit suggested speed
deactivate TrackController

activate TrackModel
TrackModel -> TrainModel : Transmit suggest speed
deactivate TrackModel

activate TrainModel
TrainModel -> TrainController : Transmit suggested speed

activate TrainController
TrainController -> TrainModel : Return power
deactivate TrainController

deactivate TrainModel

@enduml
